name:                yorhub
version:             0.1.0.0
github:              "joaovaladares/yorhub"
license:             GPL-3.0-only
author:              "Joao Valadares"
maintainer:          "joaovvaladares1@gmail.com"
copyright:           "2025 Joao Valadares"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joaovaladares/yorhub#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- vty
- text
- github
- directory
- filepath
- bytestring
- microlens
- microlens-mtl
- microlens-th

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  yorhub-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yorhub

tests:
  yorhub-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yorhub
